In [ ]:
import pandas as pd
import numpy as np

Series in Pandas

In [ ]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])

In [ ]:
print(s)

a    10
b    20
c    30
dtype: int64

In [ ]:
print(s["a"])

10

In [ ]:
print(s[0])

10

/tmp/ipython-input-209/287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

Series from Dictionary

In [ ]:
data = {"Math":90,"Physics":85,"Chemistry":88}

In [ ]:
marks=pd.Series(data)

In [ ]:
print(data)

{'Math': 90, 'Physics': 85, 'Chemistry': 88}

In [ ]:
print(marks)

Math         90
Physics      85
Chemistry    88
dtype: int64

Data Frames in Pandas

In [ ]:
data={
    "Name": ["Aman","Krish","Karan"],
    "Age": [22,23,21],
    "Marks": [85,90,88]}

In [ ]:
print(data)

{'Name': ['Aman', 'Krish', 'Karan'], 'Age': [22, 23, 21], 'Marks': [85, 90, 88]}

In [ ]:
type(data)

dict

In [ ]:
marks=pd.DataFrame(data)

In [ ]:
print(marks) #pandas automatically adds an index.This is called range index.

    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90
2  Karan   21     88

In [ ]:
marks=pd.DataFrame(data,index=["Student1","Student2","Student3"])

In [ ]:
print(marks)

           Name  Age  Marks
Student1   Aman   22     85
Student2  Krish   23     90
Student3  Karan   21     88

In [ ]:
marks.set_index("Name",inplace=True) #if we are setting inplace=True it means we are changing the original object itself.

In [ ]:
print(marks)

       Age  Marks
Name
Aman    22     85
Krish   23     90
Karan   21     88

In [ ]:
df=pd.DataFrame({
    "Name": ["Aman","Saurav","Karan"],
    "Age": [22,23,21],
    "Marks": [85,90,88]
})

In [ ]:
print(df)

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90
2   Karan   21     88

In [ ]:
df.head()

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90
2   Karan   21     88

In [ ]:
df.tail()

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90
2   Karan   21     88

In [ ]:
df=pd.DataFrame({
    "Name": ["Aman","Saurav","Karan","Shubham","Abishek","Sameer"],
    "Age": [22,23,21,22,25,26],
    "Marks": [85,90,88,90,56,70]
})

In [ ]:
df.head(2)

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90

In [ ]:
df.tail(3)

      Name  Age  Marks
3  Shubham   22     90
4  Abishek   25     56
5   Sameer   26     70

In [ ]:
df.shape

(6, 3)

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [ ]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   23.166667  79.833333
std     1.940790  13.891244
min    21.000000  56.000000
25%    22.000000  73.750000
50%    22.500000  86.500000
75%    24.500000  89.500000
max    26.000000  90.000000

Selecting the Data

In [ ]:
df["Name"]

0       Aman
1     Saurav
2      Karan
3    Shubham
4    Abishek
5     Sameer
Name: Name, dtype: object

In [ ]:
df[["Name","Marks"]]

      Name  Marks
0     Aman     85
1   Saurav     90
2    Karan     88
3  Shubham     90
4  Abishek     56
5   Sameer     70

Filtering in Pandas

In [ ]:
df[df["Marks"]>85]

      Name  Age  Marks
1   Saurav   23     90
2    Karan   21     88
3  Shubham   22     90

In [ ]:
df[(df["Age"]>21) & (df["Marks"]>85)]

      Name  Age  Marks
1   Saurav   23     90
3  Shubham   22     90

Sorting + Value Counts

In [ ]:
df.sort_values("Marks")

      Name  Age  Marks
4  Abishek   25     56
5   Sameer   26     70
0     Aman   22     85
2    Karan   21     88
3  Shubham   22     90
1   Saurav   23     90

In [ ]:
df.sort_values("Marks",ascending=False)

      Name  Age  Marks
1   Saurav   23     90
3  Shubham   22     90
2    Karan   21     88
0     Aman   22     85
5   Sameer   26     70
4  Abishek   25     56

In [ ]:
df["Age"].value_counts()

Age
22    2
23    1
21    1
25    1
26    1
Name: count, dtype: int64

Handling missing Values

In [ ]:
df=pd.DataFrame({   #updating the dataset with null values.
    "Name": ["Aman","Saurav","Karan","Shubham","Abishek","Sameer"],
    "Age" : [22,23,None,22,25,26],
    "Marks": [85,None,88,90,56,None]
})

In [ ]:
df

      Name   Age  Marks
0     Aman  22.0   85.0
1   Saurav  23.0    NaN
2    Karan   NaN   88.0
3  Shubham  22.0   90.0
4  Abishek  25.0   56.0
5   Sameer  26.0    NaN

In [ ]:
df.isnull() #checking the missing values.

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False
5  False  False   True

In [ ]:
df.isnull().sum() #counting  the missing value.

Name     0
Age      1
Marks    2
dtype: int64

In [ ]:
df.dropna()

      Name   Age  Marks
0     Aman  22.0   85.0
3  Shubham  22.0   90.0
4  Abishek  25.0   56.0

In [ ]:
print(df)

      Name   Age  Marks
0     Aman  22.0   85.0
1   Saurav  23.0    NaN
2    Karan   NaN   88.0
3  Shubham  22.0   90.0
4  Abishek  25.0   56.0
5   Sameer  26.0    NaN

GroupBy in Pandas

In [ ]:
data = ({
    "Name" : ["Aman","Saurav","Karan","Shubham","Abishek",None,"Sameer"],
    "Age" : [22,23,None,22,25,24,26],
    "Marks": [85,None,88,90,56,72,None],
    "Subject": ["Maths","Physics","Maths","Chemistry","Maths","Physics","Chemistry"]
})

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df.groupby('Subject')['Marks'].mean()

Subject
Chemistry    90.000000
Maths        76.333333
Physics      72.000000
Name: Marks, dtype: float64

In [ ]:
df.groupby('Subject')['Name'].count()

Subject
Chemistry    2
Maths        3
Physics      1
Name: Name, dtype: int64

In [ ]:
#Multiple Aggregation
df.groupby('Subject')['Marks'].agg(['mean','max','min'])

                mean   max   min
Subject
Chemistry  90.000000  90.0  90.0
Maths      76.333333  88.0  56.0
Physics    72.000000  72.0  72.0

In [ ]:
df.groupby('Subject')['Marks'].agg(['mean','max','min','count'])

                mean   max   min  count
Subject
Chemistry  90.000000  90.0  90.0      1
Maths      76.333333  88.0  56.0      3
Physics    72.000000  72.0  72.0      1

In [ ]:
df.groupby(['Subject','Age'])['Marks'].mean()

Subject    Age
Chemistry  22.0    90.0
           26.0     NaN
Maths      22.0    85.0
           25.0    56.0
Physics    23.0     NaN
           24.0    72.0
Name: Marks, dtype: float64