In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame({
    "Name" : ["John","Jane","Bob","Alice","Saima",None,"Saundarya","Khushi",None,"Nithya"],
    "Department": ["IT","Sales","HR","IT","Sales","Hr","IT","Sales","Hr","IT"],
    "Role": ["Analyst","Manager","Developer","engineer","Manager","Analyst","Agent","Analyst","Manager","Manager"],
    "Experience": [12,13,14,7,8,5,3,6,8,9],
    "Salary" : [50000,60000,70000,560000,650000,780000,860000,620000,450000,900000],
    "Score" :[70,85,None,78,83,None,88,47,90,None]
})

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
HR        70000.000000
Hr       615000.000000
IT       592500.000000
Sales    443333.333333
Name: Salary, dtype: float64

In [ ]:
df.groupby('Role')['Score'].mean()

Role
Agent        88.0
Analyst      58.5
Developer     NaN
Manager      86.0
engineer     78.0
Name: Score, dtype: float64

In [ ]:
df.groupby('Department')['Score'].count()

Department
HR       0
Hr       1
IT       3
Sales    3
Name: Score, dtype: int64

In [ ]:
df.groupby('Department').size()

Department
HR       1
Hr       2
IT       4
Sales    3
dtype: int64

In [ ]:
df.groupby('Department')['Salary'].agg(['mean','max','min','count'])

                     mean     max     min  count
Department
HR           70000.000000   70000   70000      1
Hr          615000.000000  780000  450000      2
IT          592500.000000  900000   50000      4
Sales       443333.333333  650000   60000      3

In [ ]:
df.groupby('Role')['Score'].agg(['mean','max','min','count'])

           mean   max   min  count
Role
Agent      88.0  88.0  88.0      1
Analyst    58.5  70.0  47.0      2
Developer   NaN   NaN   NaN      0
Manager    86.0  90.0  83.0      3
engineer   78.0  78.0  78.0      1

In [ ]:
df.groupby(['Department','Role'])['Salary'].mean()

Department  Role
HR          Developer     70000.0
Hr          Analyst      780000.0
            Manager      450000.0
IT          Agent        860000.0
            Analyst       50000.0
            Manager      900000.0
            engineer     560000.0
Sales       Analyst      620000.0
            Manager      355000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby(['Department','Experience'])['Score'].mean()

Department  Experience
HR          14             NaN
Hr          5              NaN
            8             90.0
IT          3             88.0
            7             78.0
            9              NaN
            12            70.0
Sales       6             47.0
            8             83.0
            13            85.0
Name: Score, dtype: float64