In [ ]:
import pandas as pd
df=pd.DataFrame({
    "Name" : ["Aman","Saurav","Karan","Shubham","Abishek",None,"Sameer"],
    "Age" : [22,23,None,22,25,24,26],
    "Marks": [85,None,88,90,56,72,None],
    "Subject": ["Maths","Physics","Maths","Chemistry","Maths","Physics","Chemistry"]
})

In [ ]:
df

      Name   Age  Marks    Subject
0     Aman  22.0   85.0      Maths
1   Saurav  23.0    NaN    Physics
2    Karan   NaN   88.0      Maths
3  Shubham  22.0   90.0  Chemistry
4  Abishek  25.0   56.0      Maths
5     None  24.0   72.0    Physics
6   Sameer  26.0    NaN  Chemistry

In [ ]:
df.shape

(7, 4)

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(df.dtypes)

Name        object
Age        float64
Marks      float64
Subject     object
dtype: object

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      float64
 2   Marks    5 non-null      float64
 3   Subject  7 non-null      object
dtypes: float64(2), object(2)
memory usage: 356.0+ bytes
None

In [ ]:
df.describe()

             Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [ ]:
df[["Name","Marks"]]

      Name  Marks
0     Aman   85.0
1   Saurav    NaN
2    Karan   88.0
3  Shubham   90.0
4  Abishek   56.0
5     None   72.0
6   Sameer    NaN

In [ ]:
df[df["Marks"]>80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0      Maths
2    Karan   NaN   88.0      Maths
3  Shubham  22.0   90.0  Chemistry

In [ ]:
df[(df["Age"]>22) & (df["Marks"]>80)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [ ]:
df["Subject"].value_counts()

Subject
Maths        3
Physics      2
Chemistry    2
Name: count, dtype: int64

In [ ]:
df.sort_values(by="Marks", ascending=False)

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0      Maths
0     Aman  22.0   85.0      Maths
5     None  24.0   72.0    Physics
4  Abishek  25.0   56.0      Maths
1   Saurav  23.0    NaN    Physics
6   Sameer  26.0    NaN  Chemistry

In [ ]:
top2 = df.nlargest(2, "Marks")
print(top2)

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0      Maths

In [ ]:
df.nsmallest(1,"Marks")

      Name   Age  Marks Subject
4  Abishek  25.0   56.0   Maths

In [ ]:
df.isnull().value_counts()

Name   Age    Marks  Subject
False  False  False  False      3
              True   False      2
       True   False  False      1
True   False  False  False      1
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [ ]:
df["Marks"].isnull()

0    False
1     True
2    False
3    False
4    False
5    False
6     True
Name: Marks, dtype: bool

In [ ]:
cleaned_data=df.dropna()
print(cleaned_data)

      Name   Age  Marks    Subject
0     Aman  22.0   85.0      Maths
3  Shubham  22.0   90.0  Chemistry
4  Abishek  25.0   56.0      Maths

In [ ]:
cleaned_data.shape

(3, 4)

In [ ]:
df.shape

(7, 4)

In [ ]:
#Q1. why marks columns has float values instead of integers?
#---> pandas convertNone to Nan and Nan is of float type.

#Using inplace=True can cause unintended data modification, makes debugging harder, breaks method chaining, and does not guarantee memory efficiency.

#The Name column contains missing values, potential spelling inconsistencies, and lacks a standardized naming format. It is recommended to make the name field mandatory, verify spelling accuracy, and introduce a unique Student ID to avoid ambiguity in student identification.